spring:
  application:
    name: TimeTracking
  datasource:
    url: jdbc:postgresql://localhost:5433/time_tracking
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger
server:
  servlet:
    context-path: /api